[versions]
android = "9.3.0"
appcompat = "1.7.1"
kotlin = "2.4.10"
kotlinCompileTesting = "0.13.0"
kotlinpoet = "2.2.0"
koin = "4.2.1"
ksp = "2.3.11"
atomicFu = "0.33.0"
kotlinxCoroutines = "1.11.0"
robolectric = "4.16.1"

[libraries]
androidx-annotations = "androidx.annotation:annotation:1.9.1"
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-testing = { module = "androidx.arch.core:core-testing", version = "2.2.0" }
androidx-junit = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-livedata = "androidx.lifecycle:lifecycle-livedata:2.9.4"
androidx-paging = "androidx.paging:paging-runtime:3.3.6"
androidx-rules = { module = "androidx.test:rules", version = "1.7.0" }
androidx-runner = { module = "androidx.test:runner", version = "1.7.0" }
androidx-sqlite = { module = "androidx.sqlite:sqlite", version = "2.5.2" }
androidx-test-core = { module = "androidx.test:core", version = "1.7.0" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
sqlCipher = "net.zetetic:android-database-sqlcipher:4.5.4"
rx = "io.reactivex.rxjava3:rxjava:3.1.12"
coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
javapoet = "com.squareup:javapoet:1.13.0"
javax-annotation = "org.glassfish:javax.annotation:10.0-b28"
junit = "junit:junit:4.13.2"

kotlinpoet = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }
kotlinpoet-javapoetInterop = { module = "com.squareup:kotlinpoet-javapoet", version.ref = "kotlinpoet" }
kotlinpoet-metadata = { module = "com.squareup:kotlinpoet-metadata", version.ref = "kotlinpoet" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }

mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:5.4.0"
mockito-core = "org.mockito:mockito-core:5.18.0"
mockito-android = "org.mockito:mockito-android:5.18.0"

kotlinCompileTesting = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlinCompileTesting" }
kotlinCompileTesting-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref = "kotlinCompileTesting" }

turbine = "app.cash.turbine:turbine:1.2.1"

atomicFu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicFu" }

sqliteJdbc = "org.xerial:sqlite-jdbc:3.50.3.0"
hikariCp = "com.zaxxer:HikariCP:6.3.0"
slf4j-api = "org.slf4j:slf4j-api:2.0.17"
slf4j-simple = "org.slf4j:slf4j-simple:2.0.17"

sqliter = "co.touchlab:sqliter-driver:1.3.3"
okio = "com.squareup.okio:okio:3.16.4"

android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
android-application = { id = "com.android.application", version.ref = "android" }
android-kmp-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android" }
legacy-kapt = { id = "com.android.legacy-kapt", version.ref = "android" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicFu" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
