package com.dbflow5.compiler

import org.jetbrains.kotlin.compiler.plugin.AbstractCliOption
import org.jetbrains.kotlin.compiler.plugin.CliOption
import org.jetbrains.kotlin.compiler.plugin.CommandLineProcessor
import org.jetbrains.kotlin.compiler.plugin.ExperimentalCompilerApi
import org.jetbrains.kotlin.config.CompilerConfiguration
import org.jetbrains.kotlin.config.CompilerConfigurationKey

internal val GENERATED_DIR_KEY = CompilerConfigurationKey<String>("com.dbflow5.compiler.generatedDir")

@OptIn(ExperimentalCompilerApi::class)
class DBFlowCommandLineProcessor : CommandLineProcessor {
    override val pluginId: String = PLUGIN_ID

    override val pluginOptions: Collection<AbstractCliOption> = listOf(
        CliOption(
            optionName = OPTION_GENERATED_DIR,
            valueDescription = "<path>",
            description = "Directory for Kotlin sources generated by the DBFlow compiler plugin",
            required = false,
        )
    )

    override fun processOption(
        option: AbstractCliOption,
        value: String,
        configuration: CompilerConfiguration,
    ) {
        when (option.optionName) {
            OPTION_GENERATED_DIR -> configuration.put(GENERATED_DIR_KEY, value)
        }
    }

    companion object {
        const val PLUGIN_ID = "com.dbflow5.compiler"
        const val OPTION_GENERATED_DIR = "generatedDir"
    }
}
