package com.dbflow5.query.property

import com.dbflow5.database.DatabaseStatement

/**
 * Description: generated by tables.
 */
data class NullablePropertyStatementWrapper<T : Any?>(
    val statementBinder: (model: T, statement: DatabaseStatement, index: Int) -> Unit,
    val nullBinder: (statement: DatabaseStatement, index: Int) -> Unit = { _, _ -> },
) {
    fun bind(model: T, statement: DatabaseStatement, startIndex: Int) {
        if (model != null) {
            statementBinder(model, statement, startIndex)
        } else {
            nullBinder(statement, startIndex)
        }
    }
}

/**
 * Description: generated by tables.
 */
data class PropertyStatementWrapper<T : Any>(
    val statementBinder: (model: T, statement: DatabaseStatement, index: Int) -> Unit,
) {
    fun bind(model: T, statement: DatabaseStatement, startIndex: Int) {
        statementBinder(model, statement, startIndex)
    }
}
